const userAuth = async (req, res, next) => {
    try {
        
    } catch (err ) {
        res.status(400).send("ERROR : " + err)
    }
}